config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	# Authentication
	# @implemented
  devise_for :users, {}

  # Application
  # @implemented
  root to: 'home#index'

  # Routes
  # @implemented
  get 'sobre' 		=> 'home#about', 			as: :about
  get 'blog'  		=> 'posts#index', 		as: :blog
  get 'post/:id'	=> 'posts#show', 			as: :post
  get 'contribua' => 'home#contribute', as: :contribute
  get 'branding' 	=> 'home#branding',   as: :branding
  get 'vagas'			=> 'jobs#index',			as: :jobs
  get 'pesquisa'  => 'home#search', 		as: :search
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/mailerable.rb
# frozen_string_literal: true

module Mailerable
	include ActiveSupport::Concern

	def mail_to(mailer, action, object = self, deliver_method = :deliver_now)
		logger = Rails.logger

		begin
			mailer.send(action.to_sym, object).send(deliver_method.to_sym)
		rescue Exception => e
			logger.warn e
			raise StandardError, e
		end
	end
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < Object
	include ActiveModel::Conversion
	include ActiveModel::Validations
	include Mailerable

	attr_accessor :name, :email, :message

	def initialize(params = {})
		@name    = params[:name]
		@email   = params[:email]
		@message = params[:message]

		@mailer  = ContactMailer
	end

	def persisted?
		false
	end

	def sendEmail
		mail_to(@mailer, :sended)
		mail_to(@mailer, :received)
	end

	validates :name,
						presence: true,
						uniqueness: false,
						allow_blank: false,
						length: { minimum: 3, maximum: 30 }

	validates :email,
						presence: true,
						uniqueness: false,
						allow_blank: false,
						length: { minimum: 3, maximum: 245 }

	validates :message,
						presence: true,
						uniqueness: false,
						allow_blank: false,
						length: { minimum: 3, maximum: 4_500 }
end

app/models/post.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  content     :text
#  description :string
#  slug        :string
#  tags        :string
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
class Post < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: [:slugged]

	self.table_name  = 'posts'
	self.primary_key = 'id'

  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  admin                  :boolean
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
	self.table_name  = 'users'
	self.primary_key = 'id'

	has_many :posts, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/branding_controller.rb
# frozen_string_literal: true

class BrandingController < ApplicationController
	def index
	end
end

app/controllers/contact_controller.rb
# frozen_string_literal: true

class ContactController < ApplicationController
	def index
		@contact = Contact.new
	end

	def create
		contact = Contact.new(contact_params)
		if contact.valid? && recaptcha_verify(model: contact)
			contact.sendEmail
			flash[:notice] = 'E-mail enviado com sucesso.'
			redirect_to root_path
		else
			render :index
		end
	end

	private

	def contact_params
		params.require(:contact).permit(:name, :email, :message)
	end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
	def index
		@posts = Post.order(created_at: :desc)
			.page(params[:page]).per(7)
	end

	def about
	end

	def contribute
	end

	def branding
	end

	def jobs
	end

	def search
	end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController < ApplicationController
	def index
	end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
	before_action :set_post, only: [:show]

	def index
		@posts = Post.order(created_at: :asc)
			.page(params[:page]).per(7)
	end

	def show
	end

	private

	def set_post
		@post = Post.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/_form.html.erb
<%= form_for(contact, { url: contact_path, method: :post }) do |f| %>
	<%= has_errors?(contact) %>

	<div class="field">
		<%= f.label :name, 'Nome Completo' %>
		<%= f.phone_field :name, class: 'form-control', required: 'required',
		placeholder: 'Digite o nome', autocomplete: 'off' %>
	</div>

	<div class="field">
		<%= f.label :email, 'E-mail' %>
		<%= f.email_field :email, class: 'form-control', required: 'required',
		placeholder: 'Digite o e-mail', autocomplete: 'off' %>
	</div>

	<div class="field">
		<%= f.label :message, 'Mensagem' %>
		<%= f.text_area :message, class: 'form-control', required: 'required',
		placeholder: 'Digite a mensagem', autocomplete: 'off' %>
	</div>

	<div class="field">
		<%= recaptcha_tags %>
	</div>

	<div class="actions"><br>
		<%= f.submit nil, class: 'btn btn-primary btn-lg top' %>
	</div>
<% end %>

app/views/contact/index.html.erb
<% provide :title, '' %>
<% provide :description, '' %>
<% provide :keywords, '' %>
<% provide :ld_json, {} %>

<section id='content'>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<%= render 'contact', contact: @contact %>
			</div>
		</div>
	</div>
</section>

app/views/home/about.html.erb
<% provide :title, '' %>
<% provide :description, '' %>
<% provide :keywords, '' %>
<% provide :ld_json, {} %>

<section id="presenter">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class='text-center'>
					<%= image_tag('railsonsb.png', class: '', width: 192, height: 192) %>
				</div>
			</div>
		</div>
	</div>
</section>

<section id='content'>
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<div class='col-md-8 col-md-offset-2'>
					<div class="row">
						<div class="col-md-12 text-center">
							<h1 class='bold'>Sobre o Rails on SB</h1>
							<p>Esse grupo é destinado a todos que desejam aprender e difundir
							conhecimento sobre Ruby & Rails, fazer networking e amigos. Teremos
							(por enquanto) dois tipos de eventos:</p>
						</div>
					</div>
					<br>

					<div class="row">
						<div class="col-md-12">
							<div class='panel panel-default'>
								<div class='panel-body'>
									<h1 class='bold'>Hacking Sessions</h1>
									<p>A melhor maneira de se tornar um desenvolvedor melhor é praticando.
									Nas Hacking Sessions iremos trabalhar em equipe para resolver um desafio
					  			proposto.</p>

					  			<%= link_to '',
					  				class: 'btn btn-primary btn-lg top rails-btn' do %>
					  				<i class="fas fa-code"></i>
					  				Acessar
					  			<% end %>
					  		</div>
					  	</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-12">
							<div class='panel panel-default'>
								<div class='panel-body'>
									<h1 class='bold'>Lighting talks:</h1>
									<p>Palestras curtas e objetivas (maximo 15 min). Iniciantes terão oportunidade
									de treinar seus skills de apresentação</p>

									<%= link_to '',
										class: 'btn btn-primary btn-lg top rails-btn' do %>
										<i class="fab fa-digital-ocean"></i>
										Acessar Conteúdo
									<% end %>
								</div>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-12">
							<%= link_to 'https://meetup.com/pt-BR/railsonsb',
							  class: 'btn btn-primary btn-lg top rails-btn' do %>
							  Junte-se a nós
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/home/branding.html.erb
<%= provide :title, '' %>
<%= provide :description, '' %>
<%= provide :keywords, '' %>
<%= provide :ld_json, {} %>

<section id="presenter">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="text-center">
					<%= image_tag('railsonsb.png', class: '', width: 192, height: 192) %>
					<h1 class='bold'>Rails on SB</h1>
					<p>Comunidade de Usuários Ruby (Rails, Sinatra, Hanami, mRuby, etc)
					de São Borja - RS.</p>
				</div>
			</div>
		</div>
	</div>
</section>

<section id='content'>
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<div class="col-md-8 col-md-offset-2">
					<div class="row">
						<div class="col-md-12">
							<h1 class='bold text-center'>Branding</h1>
						  <hr>
						</div>
					</div>

					<div class="row">
						<div class="col-md-12">
							<div class='panel panel-default'>
								<div class='panel-body'>
									<h2 class="bold">Marca/Logo</h2>
									<p>Caso precise da nossa marca/logo para divulgação ou algo do
									gênero, você pode encontrar no repositório branding no GitLab</p>
								</div>
							</div>
						</div>

						<div class="col-md-12">
							<div class='panel panel-default'>
								<div class='panel-body'>
									<h2 class="bold">Template Slides</h2>
									<p>Está preparando uma talk? para nosso próximo meetup? Fique à vontade
									para usar nosso template de slides.</p>
								</div>
							</div>
						</div>

						<div class="col-md-12">
							<div class="jumbotron">
								<h2 class='text-center uppercase'>Em Breve</h2>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/home/contribute.html.erb
<% provide :title, '' %>
<% provide :description, '' %>
<% provide :keywords, '' %>
<% provide :ld_json, {} %>

<section id="presenter">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="text-center">
					<%= image_tag('railsonsb.png', class: '', width: 192, height: 192) %>
					<h1 class='bold'>Rails on SB</h1>
					<p>Comunidade de Usuários Ruby (Rails, Sinatra, Hanami, mRuby, etc)
					de São Borja - RS.</p>
				</div>
			</div>
		</div>
	</div>
</section>

<section id='content'>
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<div class='col-md-8 col-md-offset-2'>
					<div class="row">
						<div class="col-md-12 text-center">
							<h1 class='bold'>Contribua</h1>
						  <p>Quer saber como contribuir para o nosso grupo de meetups</p>
						  <hr>
						</div>
					</div>

					<div class="row">
						<div class="col-md-12">
							<div class='panel panel-default'>
								<div class='panel-body'>
									<h2 class='bold'>1º passo - Meetup.com</h2>
									<p>Cadastre-se no Meetup e ingresse no nosso grupo.</p>

									<%= link_to '',
										class: 'btn btn-primary btn-lg top rails-btn' do %>
										<i class="fab fa-meetup"></i>
										Ir para o Meetup
									<% end %>
								</div>
							</div>
						</div>

						<div class="col-md-12">
							<div class='panel panel-default'>
								<div class='panel-body'>
									<h2 class='bold'>2º passo - Slack</h2>
									<p>Entre em nosso Slack para participar das discussões e da comunidade.</p>

									<%= link_to 'https://join.slack.com/t/railsonsb/shared_invite/zt-pskjwcgy-uSc~rR35IzOpxBq9kfjnOg',
										class: 'btn btn-primary btn-lg top rails-btn' do %>
										<i class="fab fa-slack"></i>
										Entrar para o Slack
									<% end %>
								</div>
							</div>
						</div>

						<div class="col-md-12">
							<div class='panel panel-default'>
								<div class='panel-body'>
									<h2 class='bold'>3º Passo - Gitlab e Github</h2>
									<p>Temos repositórios nos dois!</p>

									<ul class="list-unstyled list-inline">
										<li>
											<%= link_to 'https://github.com/Rails-on-SB',
												class: 'btn btn-primary btn-lg top rails-btn' do %>
													<i class="fab fa-github"></i>
													Github
											<% end %>
										</li>
										<li>
											<%= link_to 'https://gitlab.com/renatorfranco18/rails-on-sb',
												class: 'btn btn-primary btn-lg top rails-btn' do %>
													<i class="fab fa-gitlab"></i>
													GitLab
											<% end %>
										</li>
									</ul>
								</div>
							</div>
						</div>

						<div class="col-md-12">
							<p>Este site que você esta acessando utiliza Jekill e
							qualquer um pode contribuir, dê uma olhada no repositório
						  no GitLab. Temos alguns desafios no GitHub, caso queira treinar algum ou
						  contribuir adicionado mais desafios.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/home/index.html.erb
<% provide :title, '' %>
<% provide :description, '' %>
<% provide :keywords, '' %>
<% provide :ld_json, {} %>

<section id="presenter">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="text-center">
					<%= image_tag('railsonsb.png', class: '', width: 192, height: 192) %>
					<h1 class='bold'>Rails on SB</h1>
					<p>Comunidade de Usuários Ruby (Rails, Sinatra, Hanami, mRuby, etc)
					de São Borja - RS.</p>
				</div>
			</div>
		</div>
	</div>
</section>

<section id='content'>
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<div class='col-md-8 col-md-offset-2'>
					<div class="row">
						<div class="text-center">
							<h1 class='bold'>Artigos e Meetups</h1>
							<hr>
						</div>
					</div>

					<div class="row">
						<div class="col-md-12">
							<% @posts.each do |post| %>
								<div class="col-md-12">
									<div class="panel panel-default">
										<div class="panel-body">
											<span class='pull-right bold uppercase'>
												<i class="far fa-clock"></i>
												<%= time_ago_in_words(post.created_at) %>
											</span>
											<h3 class='bold'><%= link_to post.title, post_path(post.id) %></h3>
											<p><%= truncate(post.content, length: 245) %></p>
										</div>
									</div>
								</div>
							<% end %>

							<% if @posts.empty? %>
								<div class="well">
									<p class="text-center">
										Nenhuma post/arquivo encontrado :(
									</p>
								</div>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/home/search.html.erb
<%= provide :title, '' %>
<%= provide :description, '' %>
<%= provide :keywords, '' %>
<%= provide :ld_json, {} %>

<section id="presenter">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="text-center">
					<%= image_tag('railsonsb.png', class: '', width: 192, height: 192) %>
					<h1 class='bold'>Rails on SB</h1>
					<p>Comunidade de Usuários Ruby (Rails, Sinatra, Hanami, mRuby, etc)
					de São Borja - RS.</p>
				</div>
			</div>
		</div>
	</div>
</section>

<section id='content'>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<br>

				<div class='col-md-8 col-md-offset-2'>
					<div class='row'>
						<%= form_for(:search, { url: '', method: :get }) do |f| %>

							<div class="field col-md-10">
								<%= f.search_field :search, class: 'form-control',
								required: 'required', placeholder: 'O que você está buscando?',
								style: 'height: 45px;' %>
							</div>

							<div class="actions col-md-2">
								<%= f.submit 'Buscar',
								class: 'btn btn-primary btn-lg top rails-btn',
								style: 'margin-left: -20px;' %>
							</div>
						<% end %>
					</div>
				</div>

			</div>
		</div>
	</div>
</section>

app/views/jobs/index.html.erb
<%= provide :title, '' %>
<%= provide :description, '' %>
<%= provide :keywords, '' %>
<%= provide :ld_json, {} %>

<section id="presenter">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="text-center">
					<%= image_tag('railsonsb.png', class: '', width: 192, height: 192) %>
					<h1 class='bold'>Rails on SB</h1>
					<p>Comunidade de Usuários Ruby (Rails, Sinatra, Hanami, mRuby, etc)
					de São Borja - RS.</p>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="content">
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<br>
				<div class='col-md-8 col-md-offset-2'>
					<div class="text-center well">
						<h2 class='text-center uppercase'>Em Breve</h2>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/layouts/_footer.html.erb
<footer id='footer'>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="col-md-6 col-md-offset-3 text-center">
					<ul class='list-unstyled list-inline inner'>
						<li>
							<%= link_to 'https://github.com/railsonsb' do %>
								<i class="fas fa-user-astronaut"></i>
								Código de conduta
							<% end %>
						</li>
						<li>
							<%= link_to 'https://meetup.com/pt-BR/railsonsb' do %>
								<i class="fab fa-meetup"></i>
								Meetup
							<% end %>
						</li>
						<li>
							<%= link_to 'https://slack.com/railsonsb' do %>
								<i class="fab fa-slack"></i>
								Slack
							<% end %>
						</li>
					</ul>

					<p>&copy <%= Date.today.year %>
					Rails on SB. Feito por <span class='bold'>Renato Franco</span></p>
					<ul class='list-unstyled list-inline'>
						<li>
							<%= link_to 'https://twitter.com/railsonsb' do %>
								<i class="fab fa-twitter"></i>
							<% end %>
						</li>
						<li>
							<%= link_to 'https://facebook.com/railsonsb' do %>
								<i class="fab fa-facebook-square"></i>
							<% end %>
						</li>
						<li>
							<%= link_to 'https://instagram.com/railsonsb' do %>
								<i class="fab fa-instagram"></i>
							<% end %>
						</li>
						<li>
							<%= link_to 'https://github.com/railsonsb' do %>
								<i class="fab fa-github"></i>
							<% end %>
						</li>
						<li>
							<%= link_to 'https://youtube.com/railsonsb' do %>
								<i class="fab fa-youtube"></i>
							<% end %>
						</li>
						<li>
							<%= link_to '/rss' do %>
								<i class="fas fa-rss"></i>
							<% end %>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar navbar-default">
  <div class="container container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to root_path,
      	class: 'navbar-brand' do %>
      		<%= image_tag('railsonsb.png', class: '', width: 30, height: 30) %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
   			<li><%= link_to 'Início', root_path %></li>
   			<li><%= link_to 'Sobre', about_path %></li>
   			<li><%= link_to 'Blog', blog_path %></li>
   			<li><%= link_to 'Contribua', contribute_path %></li>
   			<li><%= link_to 'Branding', branding_path %></li>
   			<li><%= link_to 'Vagas', jobs_path %></li>
   			<li><%= link_to 'Pesquisa', search_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title>Rails On SB</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type='text/css'><%= yield :css %></style>
    <script type="text/javascript"><%= yield :js %></script>
    <script type="application/ld+json"><%= yield :ld_json %></script>
    <script src="https://kit.fontawesome.com/5165849ba2.js" crossorigin="anonymous"></script>
  </head>
  <body class="<%= controller.controller_name %>" data-spy="scroll">
    <%= render partial: 'layouts/header' %>
      <%= yield %>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/posts/index.html.erb
<% provide :title, '' %>
<% provide :description, '' %>
<% provide :keywords, '' %>
<% provide :ld_json, {} %>

<section id="presenter">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="text-center">
					<%= image_tag('railsonsb.png', class: '', width: 192, height: 192) %>
					<h1 class='bold'>Rails on SB</h1>
					<p>Comunidade de Usuários Ruby (Rails, Sinatra, Hanami, mRuby, etc)
					de São Borja - RS.</p>
				</div>
			</div>
		</div>
	</div>
</section>

<section id='content'>
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<div class='col-md-8 col-md-offset-2'>
					<div class="row text-center">
						<h1 class='bold'>Artigos e Meetups</h1>
						<hr>
					</div>

					<div class="row">
						<div class="col-md-12">
							<% @posts.each do |post| %>
								<div class="col-md-12">
									<div class="panel panel-default">
										<div class="panel-body">
											<span class='pull-right bold uppercase'>
												<i class="far fa-clock"></i>
												<%= time_ago_in_words(post.created_at) %>
											</span>
											<h3 class='bold'><%= link_to post.title, post_path(post.id) %></h3>
											<p><%= truncate(post.content, length: 245) %></p>
										</div>
									</div>
								</div>
							<% end %>

							<% if @posts.empty? %>
								<div class="well">
									<p class="text-center">
										Nenhuma post/arquivo encontrado :(
									</p>
								</div>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/posts/show.html.erb
<% provide :title, @post.title %>
<% provide :description, @post.description %>
<% provide :keywords, @post.tags %>
<% provide :ld_json, {} %>

<section id="presenter">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="text-center">
					<%= image_tag('railsonsb.png', class: '', width: 140, height: 140) %>
					<h1 class='bold'>Rails on SB</h1>
					<p>Comunidade de Usuários Ruby (Rails, Sinatra, Hanami, mRuby, etc)
					de São Borja - RS.</p>
				</div>
			</div>
		</div>
	</div>
</section>

<section id='content'>
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<div id="tags" style='padding-top: 40px; margin-left: 20px;'>
					<div class="row">
						<div class="col-md-12">
							<% @post.tags.split('#').each do |tag| %>
								<span class='bold' style='text-transform: uppercase;'><%= tag %></span>
							<% end %>
						</div>
					</div>
				</div>

				<div id="title">
					<div class="row">
						<div class="col-md-12 text-center">
							<h1 class='bold'><%= @post.title %></h1>
							<hr>
						</div>
					</div>
				</div>

				<div id="content">
					<div class="row">
						<div class="col-md-3">

              <div class="col-md-12">
              	<div class='panel panel-default'>
              		<div class='panel-body text-center'>
              			<%= image_tag('railsonsb.png', class: '', width: 124, height: 124) %>
              		</div>
              	</div>
              </div>

              <div class="col-md-12">
              	<div class="panel panel-default">
              		<div class="panel-body">
              			<ul class='nav nav-pills nav-stacked'>
              				<li>
              					<i class="fas fa-user-astronaut"></i>
              					<span class='bold'><%= @post.user.name %></span>
              				</li>
              				<li>
              					<i class="far fa-calendar-alt"></i>
              					<%= time_ago_in_words(@post.created_at) %>
              				</li>
              				<li>
              					<i class="far fa-comments"></i>
              					<%= rand(1..15) %> Comentários
              				</li>
              				<li>
              					<i class="fab fa-twitter"></i>
              					Tweetar
              				</li>
              				<li>
              					<i class="fas fa-thumbs-up"></i>
              					Curtir
              				</li>
              				<li>
              					<i class="fab fa-google-plus"></i>
              					+1
              				</li>
              			</ul>
              		</div>
              	</div>
              </div>
						</div>

						<div class="col-md-9">
							<div class="col-md-12">
								<%= @post.content %>
							</div>

							<hr>
							<div class="col-md-12" style='margin-top: 30px;'>
								<div id="disqus_thread"></div>
								<script>
								    /**
								    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
								    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
								    /*
								    var disqus_config = function () {
								    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
								    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
								    };
								    */
								    (function() { // DON'T EDIT BELOW THIS LINE
								    var d = document, s = d.createElement('script');
								    s.src = 'https://rails-on-sb.disqus.com/embed.js';
								    s.setAttribute('data-timestamp', +new Date());
								    (d.head || d.body).appendChild(s);
								    })();
								</script>
								<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
</section>